//
// tools/ui-lint/lib/constants.mjs
// Copyright (C) 2026 Gill-Bates http://github.com/Gill-Bates
//

// Shared constants for the UI lint tool.

export const VERTICAL_GAP_MIN = 22;
export const VERTICAL_GAP_MAX = 26;
export const STACK_GAP_VARIANCE_TOLERANCE_PX = 2;
export const VISUAL_DRIFT_THRESHOLD = 0.0025;
export const SCREENSHOT_SETTLE_MS = 800;
export const TAB_SWITCH_SETTLE_MS = 700;
export const DETAILS_EXPAND_SETTLE_MS = 300;
export const OVERFLOW_TOLERANCE_PX = 6;
export const FOOTER_OVERLAP_TOLERANCE_PX = 1;
export const SCROLL_EDGE_CLEARANCE_MIN = 12;
export const LAYOUT_SHIFT_THRESHOLD = 0.02;
export const COMPONENT_LAYOUT_SHIFT_THRESHOLD_PX = 2;
export const COMPONENT_LAYOUT_SHIFT_SETTLE_MS = 800;
export const CLICK_TARGET_MIN_SIZE_PX = 44;
export const LOGIN_ERROR_SETTLE_MS = 120;
export const LOGIN_LOCKOUT_RESET_MS = 16000;
export const LOGIN_TEST_STAGGER_MS = 13000;
export const LOGS_DELETE_HAIRLINE_TOLERANCE_PX = 2;
export const BADGE_FONT_SIZE_TOLERANCE_PX = 0.5;
export const BADGE_FONT_WEIGHT_TOLERANCE = 50;
export const BADGE_RADIUS_TOLERANCE_PX = 1;
export const BADGE_PADDING_TOLERANCE_PX = 1;
export const MONOSPACE_RADIUS_TOLERANCE_PX = 1;
export const MONOSPACE_PADDING_TOLERANCE_PX = 1;
export const SLIDER_TICK_ALIGNMENT_TOLERANCE_PX = 3;
export const SLIDER_VISIBLE_LABEL_GAP_MIN_PX = 4;
export const SLIDER_LABEL_HIDDEN_OPACITY_MAX = 0.05;
export const MODAL_BACKDROP_BLUR_EXPECTED_PX = 8;
export const MODAL_BACKDROP_BLUR_TOLERANCE_PX = 0.25;
export const MODAL_BACKDROP_SATURATE_EXPECTED = 0.8;
export const MODAL_BACKDROP_SATURATE_TOLERANCE = 0.05;
export const MODAL_BACKDROP_ALPHA_EXPECTED = 0.6;
export const MODAL_BACKDROP_ALPHA_TOLERANCE = 0.05;
export const FORM_SWITCH_MAX_HEIGHT_PX = 22;
export const FORM_SWITCH_HEIGHT_TOLERANCE_PX = 1;
export const FLEX_MIN_HEIGHT_ZERO_TOLERANCE_PX = 0.5;
export const INPUT_GROUP_HEIGHT_EXPECTED_PX = 44;
export const INPUT_GROUP_HEIGHT_TOLERANCE_PX = 2;
export const COMPACT_CARD_ACTION_MARGIN_TOP_MAX_PX = 10;
export const COMPACT_CARD_ACTION_PADDING_TOP_MAX_PX = 2;
export const COMPACT_CARD_ACTION_BORDER_TOP_MAX_PX = 0.5;
export const GHOST_SCROLL_DELTA_MAX_PX = 8;
export const GHOST_SCROLL_MIN_HEIGHT_PX = 120;
export const KPI_CARD_PADDING_EXPECTED = 16;
export const KPI_CARD_PADDING_TOLERANCE = 1;
export const KPI_ICON_MIN = 32;
export const KPI_ICON_MAX = 40;
export const KPI_VISUAL_DRIFT_THRESHOLD = 0.01;
export const KPI_HEIGHT_TOLERANCE_PX = 2;
export const KPI_ROW_VARIANCE_MAX = 3;
export const KPI_ICON_CENTER_TOLERANCE_PX = 4;
export const KPI_ICON_NEUTRAL_COLOR_DISTANCE_MAX = 12;
export const KPI_CONTEXTUAL_ICON_CLASSES = ['text-primary', 'text-success', 'text-info', 'text-danger', 'text-warning'];
export const SETTINGS_TAB_COLOR_DISTANCE_MAX = 12;
export const DASHBOARD_TRANSFER_COLOR_DISTANCE_MIN = 40;
export const KPI_CARD_REQUIRED_SCOPES = ['dashboard', 'dns'];
export const CARD_BORDER_RADIUS_EXPECTED_PX = 12;
export const CARD_BORDER_RADIUS_TOLERANCE_PX = 1;
export const ABOUT_TOP_ROW_HEIGHT_TOLERANCE_PX = 2;
export const ABOUT_MOBILE_STACK_GAP_VARIANCE_TOLERANCE_PX = 2;
export const ABOUT_APPLICATION_DETAILS_REQUIRED_ROWS = ['Version', 'Python', 'Timezone', 'WireGuard', 'Unbound'];
export const ABOUT_APPLICATION_DETAILS_FORBIDDEN_ROWS = ['Build'];
export const ABOUT_UPDATE_TABLE_LABELS = ['Current', 'Latest', 'Released'];
export const THEMES = ['light', 'dark'];

export const WCAG_CONTRAST = {
    NORMAL_AA: 4.5,
    LARGE_AA: 3.0,
    LARGE_TEXT_SIZE_PX: 24,
    LARGE_TEXT_SIZE_BOLD_PX: 18.66,
    BOLD_WEIGHT: 700,
};

export const STATUS_FLOW_NODE_EXPECTATIONS = [
    { key: 'client', label: 'Client', icon: 'devices' },
    { key: 'wireguard', label: 'WireGuard', icon: 'vpn_lock' },
    { key: 'internet', label: 'Internet', icon: 'public' },
];

export const STATUS_FLOW_CONNECTOR_EXPECTATIONS = [
    'client-wireguard',
    'wireguard-internet',
];

export const STATUS_DETAIL_CARD_TITLES = ['Public Client IP', 'Outbound IP'];

export const MOTION_RESET_CSS = `
  *, *::before, *::after {
    animation: none !important;
    transition: none !important;
    scroll-behavior: auto !important;
    caret-color: transparent !important;
  }
`;

export const APP_SPECIFIC_MOTION_RESET_CSS = `
  .pulse-marker,
  .leaflet-pane,
  .leaflet-control-container,
  #peer-map img,
  #peer-map canvas {
    animation: none !important;
    transition: none !important;
  }
`;

export const FULL_MOTION_RESET_CSS = MOTION_RESET_CSS + APP_SPECIFIC_MOTION_RESET_CSS;

export const UI_EVAL_CONSTANTS = {
    OVERFLOW_TOLERANCE_PX,
    FOOTER_OVERLAP_TOLERANCE_PX,
    VERTICAL_GAP_MIN,
    VERTICAL_GAP_MAX,
    STACK_GAP_VARIANCE_TOLERANCE_PX,
    SCROLL_EDGE_CLEARANCE_MIN,
    GHOST_SCROLL_DELTA_MAX_PX,
    GHOST_SCROLL_MIN_HEIGHT_PX,
    COMPONENT_LAYOUT_SHIFT_THRESHOLD_PX,
    COMPONENT_LAYOUT_SHIFT_SETTLE_MS,
    CLICK_TARGET_MIN_SIZE_PX,
    LOGS_DELETE_HAIRLINE_TOLERANCE_PX,
    BADGE_FONT_SIZE_TOLERANCE_PX,
    BADGE_FONT_WEIGHT_TOLERANCE,
    BADGE_RADIUS_TOLERANCE_PX,
    BADGE_PADDING_TOLERANCE_PX,
    MONOSPACE_RADIUS_TOLERANCE_PX,
    MONOSPACE_PADDING_TOLERANCE_PX,
    SLIDER_TICK_ALIGNMENT_TOLERANCE_PX,
    SLIDER_VISIBLE_LABEL_GAP_MIN_PX,
    SLIDER_LABEL_HIDDEN_OPACITY_MAX,
    MODAL_BACKDROP_BLUR_EXPECTED_PX,
    MODAL_BACKDROP_BLUR_TOLERANCE_PX,
    MODAL_BACKDROP_SATURATE_EXPECTED,
    MODAL_BACKDROP_SATURATE_TOLERANCE,
    MODAL_BACKDROP_ALPHA_EXPECTED,
    MODAL_BACKDROP_ALPHA_TOLERANCE,
    FORM_SWITCH_MAX_HEIGHT_PX,
    FORM_SWITCH_HEIGHT_TOLERANCE_PX,
    FLEX_MIN_HEIGHT_ZERO_TOLERANCE_PX,
    INPUT_GROUP_HEIGHT_EXPECTED_PX,
    INPUT_GROUP_HEIGHT_TOLERANCE_PX,
    COMPACT_CARD_ACTION_MARGIN_TOP_MAX_PX,
    COMPACT_CARD_ACTION_PADDING_TOP_MAX_PX,
    COMPACT_CARD_ACTION_BORDER_TOP_MAX_PX,
    CARD_BORDER_RADIUS_EXPECTED_PX,
    CARD_BORDER_RADIUS_TOLERANCE_PX,
    KPI_ICON_CENTER_TOLERANCE_PX,
    KPI_ICON_NEUTRAL_COLOR_DISTANCE_MAX,
    KPI_CONTEXTUAL_ICON_CLASSES,
    DASHBOARD_TRANSFER_COLOR_DISTANCE_MIN,
    ABOUT_TOP_ROW_HEIGHT_TOLERANCE_PX,
    ABOUT_MOBILE_STACK_GAP_VARIANCE_TOLERANCE_PX,
    ABOUT_APPLICATION_DETAILS_REQUIRED_ROWS,
    ABOUT_APPLICATION_DETAILS_FORBIDDEN_ROWS,
    ABOUT_UPDATE_TABLE_LABELS,
    STATUS_FLOW_NODE_EXPECTATIONS,
    STATUS_FLOW_CONNECTOR_EXPECTATIONS,
    STATUS_DETAIL_CARD_TITLES,
    WCAG_NORMAL_AA: WCAG_CONTRAST.NORMAL_AA,
    WCAG_LARGE_AA: WCAG_CONTRAST.LARGE_AA,
    WCAG_LARGE_TEXT_SIZE_PX: WCAG_CONTRAST.LARGE_TEXT_SIZE_PX,
    WCAG_LARGE_TEXT_SIZE_BOLD_PX: WCAG_CONTRAST.LARGE_TEXT_SIZE_BOLD_PX,
    WCAG_BOLD_WEIGHT: WCAG_CONTRAST.BOLD_WEIGHT,
};
