//
// tools/ui-lint/lib/findings/policies/layout-policy.mjs
// Copyright (C) 2026 Gill-Bates http://github.com/Gill-Bates
//

import { countFindingRule, customFindingRule, flagFindingRule, thresholdFindingRule } from '../engine/policy-engine.mjs';

export function buildLayoutPolicy() {
    return {
        id: 'layout-policy',
        owner: 'platform-ui',
        rules: [
            customFindingRule({
                id: 'horizontal-overflow',
                type: 'horizontal-overflow',
                category: 'layout',
                severity: 'error',
                build(context) {
                    const overflow = context.metrics.horizontalOverflow || {};
                    if (!overflow.hasOverflow) return [];
                    return [{
                        id: 'horizontal-overflow',
                        type: 'horizontal-overflow',
                        category: 'layout',
                        severity: 'error',
                        count: overflow.offenders?.length || 1,
                        value: overflow,
                        message: 'Horizontal overflow detected',
                        explanation: 'Content exceeds the viewport width and can break interaction or visual containment.',
                        remediation: 'Constrain the offending container, or apply min-width:0 to flex items.',
                        legacyKey: 'horizontalOverflow',
                        confidence: 0.96,
                        wcag: ['1.4.10'],
                    }];
                },
            }),
            countFindingRule({
                id: 'overflow-offenders',
                type: 'overflow-offenders',
                category: 'layout',
                severity: 'error',
                metricPath: 'metrics.horizontalOverflow.offenders',
                legacyKey: (context, count) => `overflowOffenders=${count}`,
                message: 'Overflow offenders detected',
                explanation: 'One or more elements are causing the horizontal overflow condition.',
                remediation: 'Inspect the listed offenders and fix their width constraints.',
            }),
            countFindingRule({
                id: 'clipped-buttons',
                type: 'clipped-buttons',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.clippedButtons',
                legacyKey: (context, count) => `clippedButtons=${count}`,
                message: 'Clipped buttons detected',
                explanation: 'Buttons are visually clipped by their container or stacking context.',
                remediation: 'Adjust container overflow or spacing so controls remain fully visible.',
            }),
            countFindingRule({
                id: 'button-text-not-centered',
                type: 'button-text-not-centered',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.buttonTextNotCentered',
                legacyKey: (context, count) => `buttonTextNotCentered=${count}`,
                message: 'Button text not vertically centered',
                explanation: 'Button content is not vertically centered within the button, often caused by min-height without flexbox alignment.',
                remediation: 'Add display:flex; align-items:center; justify-content:center; to the button CSS.',
            }),
            customFindingRule({
                id: 'standard-button-height-contract',
                type: 'standard-button-height-contract',
                category: 'layout',
                severity: 'error',
                build(context) {
                    const contract = context.metrics.standardButtonHeightContract;
                    if (!contract || contract.mismatchCount <= 0) {
                        return [];
                    }

                    return [{
                        id: 'standard-button-height-contract',
                        type: 'standard-button-height-contract',
                        category: 'layout',
                        severity: 'error',
                        count: contract.mismatchCount,
                        value: contract.sample,
                        message: 'Standard buttons mismatch the shared height token',
                        explanation: 'Standard .btn and .wb-btn controls drift away from the shared form input height token, causing inconsistent action sizing.',
                        remediation: 'Align standard buttons to var(--wb-input-height) or the shared button component token and keep compact/large variants as explicit exceptions.',
                        legacyKey: `standardButtonHeightContract=${contract.mismatchCount}`,
                    }];
                },
            }),
            countFindingRule({
                id: 'dropdown-toggle-click-failures',
                type: 'dropdown-toggle-click-failures',
                category: 'layout',
                severity: 'error',
                metricPath: 'metrics.dropdownToggleClickFailures',
                legacyKey: (context, count) => `dropdownToggleClickFailures=${count}`,
                message: 'Dropdown toggle is not reliably clickable',
                explanation: 'A visible dropdown toggle does not receive the hit target correctly or fails to open its menu when clicked.',
                remediation: 'Ensure the button is the top hit target and bind the dropdown toggle directly so a click opens the menu.',
            }),
            countFindingRule({
                id: 'ghost-scroll',
                type: 'ghost-scroll',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.ghostScroll',
                legacyKey: () => 'ghostScrollDetected',
                message: 'Ghost scroll detected',
                explanation: 'The page can scroll unexpectedly even though the visible content does not justify it.',
                remediation: 'Remove unintended overflow or adjust the scroll container boundaries.',
            }),
            countFindingRule({
                id: 'ghost-scroll-containers',
                type: 'ghost-scroll-containers',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.ghostScrollContainers',
                legacyKey: (context, count) => `ghostScrollContainers=${count}`,
                message: 'Ghost scroll containers detected',
                explanation: 'Unexpected scroll containers can create double-scroll or clipping issues.',
                remediation: 'Collapse nested scroll regions into a single explicit scroller.',
            }),
            countFindingRule({
                id: 'scrollbar-gutter-risks',
                type: 'scrollbar-gutter-risks',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.scrollbarGutterRisks',
                legacyKey: (context, count) => `scrollbarGutterRisks=${count}`,
                message: 'Scrollbar gutter risks detected',
                explanation: 'Layout may shift when scrollbars appear or disappear.',
                remediation: 'Reserve gutter space or size containers for scrollbar presence.',
            }),
            countFindingRule({
                id: 'safari-table-overflow-risks',
                type: 'safari-table-overflow-risks',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.safariTableOverflowRisks',
                legacyKey: (context, count) => `safariTableOverflowRisks=${count}`,
                message: 'Safari table overflow risk detected',
                explanation: 'Table layout may overflow in WebKit due to width calculation differences.',
                remediation: 'Recheck table wrapper sizing and avoid unconstrained min-content cells.',
            }),
            countFindingRule({
                id: 'bootstrap-grid-issues',
                type: 'bootstrap-grid-issues',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.bootstrapGridIssues',
                legacyKey: (context, count) => `bootstrapGridIssues=${count}`,
                message: 'Bootstrap grid issues detected',
                explanation: 'The grid structure is not matching Bootstrap layout expectations.',
                remediation: 'Use valid row/column nesting and verify container widths.',
            }),
            countFindingRule({
                id: 'bootstrap-columns-outside-rows',
                type: 'bootstrap-columns-outside-rows',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.bootstrapColumnsOutsideRows',
                legacyKey: (context, count) => `bootstrapColumnsOutsideRows=${count}`,
                message: 'Bootstrap columns outside rows detected',
                explanation: 'Columns should be nested inside rows to preserve grid semantics.',
                remediation: 'Wrap columns in a row or refactor the layout container structure.',
            }),
            countFindingRule({
                id: 'breakpoint-display-conflicts',
                type: 'breakpoint-display-conflicts',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.breakpointDisplayConflicts',
                legacyKey: (context, count) => `breakpointDisplayConflicts=${count}`,
                message: 'Breakpoint display conflicts detected',
                explanation: 'Responsive visibility rules conflict with the current breakpoint.',
                remediation: 'Align breakpoint-specific display utilities with the intended layout state.',
            }),
            countFindingRule({
                id: 'navbar-collapse-issues',
                type: 'navbar-collapse-issues',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.navbarCollapseIssues',
                legacyKey: (context, count) => `navbarCollapseIssues=${count}`,
                message: 'Navbar collapse issues detected',
                explanation: 'Navbar responsiveness is broken or not matching collapse behavior.',
                remediation: 'Check collapse markup and breakpoint-specific navigation structure.',
            }),
            thresholdFindingRule({
                id: 'layout-shift',
                type: 'layout-shift',
                category: 'layout-stability',
                severity: 'error',
                metricPath: 'metrics.layoutShift.value',
                threshold: (context) => context.metrics.layoutShift?.threshold ?? 0.02,
                legacyKey: (context, value) => `layoutShift=${Number(value).toFixed(4)}`,
                message: 'Layout shift threshold exceeded',
                explanation: 'The layout moved more than the stability budget allows.',
                remediation: 'Reduce asynchronous layout changes or reserve space before content loads.',
            }),
            countFindingRule({
                id: 'component-layout-shift',
                type: 'component-layout-shift',
                category: 'layout-stability',
                severity: 'warning',
                metricPath: 'metrics.componentLayoutShift',
                legacyKey: (context, count) => `componentLayoutShift=${count}`,
                message: 'Component layout shift detected',
                explanation: 'A component is moving during rendering or hydration.',
                remediation: 'Stabilize the component size before replacing or loading its content.',
            }),
            countFindingRule({
                id: 'row-to-row-gap',
                type: 'row-to-row-gap',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.spacing.outlierVerticalGaps',
                legacyKey: (context, count) => `outlierVerticalGaps=${count}`,
                message: 'Vertical gap outliers detected',
                explanation: 'Spacing between rows is outside the policy range.',
                remediation: 'Align row spacing with the layout token scale.',
            }),
            customFindingRule({
                id: 'double-scroll-risk',
                type: 'double-scroll-risk',
                category: 'layout',
                severity: 'warning',
                build(context) {
                    const issue = context.metrics.doubleScrollRisk;
                    if (!issue) return [];
                    return [{
                        id: 'double-scroll-risk',
                        type: 'double-scroll-risk',
                        category: 'layout',
                        severity: context.device === 'mobile' ? 'error' : 'warning',
                        count: issue.innerScrollCount,
                        value: issue,
                        message: 'Double scroll risk detected',
                        explanation: 'The page contains nested scrolling regions that compete for user interaction.',
                        remediation: 'Keep one scroll owner per axis and avoid nested overflow containers.',
                        legacyKey: `doubleScroll=${issue.innerScrollCount}`,
                        confidence: 0.91,
                    }];
                },
            }),
            countFindingRule({
                id: 'nested-scroll-containers',
                type: 'nested-scroll-containers',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.nestedScrollContainers',
                legacyKey: (context, count) => `nestedScrollContainers=${count}`,
                message: 'Nested scroll containers detected',
                explanation: 'Nested scrollers make wheel/touch behavior unpredictable.',
                remediation: 'Collapse nested scroll containers or clearly partition scroll ownership.',
            }),
            countFindingRule({
                id: 'flex-scroll-traps',
                type: 'flex-scroll-traps',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.flexScrollTraps',
                legacyKey: (context, count) => `flexScrollTraps=${count}`,
                message: 'Flex scroll traps detected',
                explanation: 'Flex layouts can trap scrolling content without an explicit scroll boundary.',
                remediation: 'Ensure flex children shrink appropriately and the scroll boundary is intentional.',
            }),
            countFindingRule({
                id: 'card-containment',
                type: 'card-containment',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.cardContainment.cardsPastFooter',
                legacyKey: (context, count) => `cardsPastFooter=${count}`,
                message: 'Cards extend past the footer',
                explanation: 'Card layout exceeds its expected container bounds.',
                remediation: 'Reduce the card height or allow the parent container to expand.',
            }),
            countFindingRule({
                id: 'overlay-above-footer',
                type: 'overlay-above-footer',
                category: 'layout',
                severity: 'error',
                metricPath: 'metrics.cardContainment.overlaysAboveFooter',
                legacyKey: (context, count) => `overlaysAboveFooter=${count}`,
                message: 'Overlay z-index exceeds footer',
                explanation: 'An overlay has a z-index higher than the footer, causing it to scroll over the footer.',
                remediation: 'Reduce the overlay z-index to be lower than the footer (z-index: 1000) or use overflow: hidden on the parent.',
            }),
            countFindingRule({
                id: 'unnecessary-scroll-box',
                type: 'unnecessary-scroll-box',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.cardContainment.unnecessaryScrollBoxes',
                legacyKey: (context, count) => `unnecessaryScrollBoxes=${count}`,
                message: 'Box has unnecessary scroll constraint',
                explanation: 'A content box has max-height causing scrolling when the content could fit if the constraint was removed.',
                remediation: 'Remove the max-height constraint or increase it to fit the content without scrolling.',
            }),
            countFindingRule({
                id: 'clipped-dropdown',
                type: 'clipped-dropdown',
                category: 'layout',
                severity: 'error',
                metricPath: 'metrics.cardContainment.clippedDropdowns',
                legacyKey: (context, count) => `clippedDropdowns=${count}`,
                message: 'Dropdown menu may be clipped by overflow container',
                explanation: 'A dropdown is inside a container with overflow:hidden/auto/scroll which can clip the dropdown menu.',
                remediation: 'Use position:fixed on .dropdown-menu or configure Bootstrap dropdown with popperConfig.strategy="fixed".',
            }),
            countFindingRule({
                id: 'visual-containment',
                type: 'visual-containment',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.visualContainmentIssues',
                legacyKey: (context, count) => `visualContainmentIssues=${count}`,
                message: 'Visual containment issues detected',
                explanation: 'An element renders outside its intended visual boundary.',
                remediation: 'Adjust clipping, stacking, or sizing so the content stays within bounds.',
            }),
            countFindingRule({
                id: 'form-switch-margin',
                type: 'form-switch-margin',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.formSwitchMarginIssues',
                legacyKey: (context, count) => `formSwitchMarginIssues=${count}`,
                message: 'Form switch margin issues detected',
                explanation: 'Switch components are not aligned to the spacing contract.',
                remediation: 'Adjust margins to match the component spacing token.',
            }),
            countFindingRule({
                id: 'form-switch-proportion',
                type: 'form-switch-proportion',
                category: 'layout',
                severity: 'error',
                metricPath: 'metrics.formSwitchProportionIssues',
                legacyKey: (context, count) => `formSwitchProportionIssues=${count}`,
                message: 'Form switch proportion issues detected',
                explanation: 'Switch proportions do not match the expected control geometry.',
                remediation: 'Restore the expected switch sizing and proportions.',
            }),
            countFindingRule({
                id: 'form-switch-height',
                type: 'form-switch-height',
                category: 'layout',
                severity: 'error',
                metricPath: 'metrics.formSwitchHeightIssues',
                legacyKey: (context, count) => `formSwitchHeightIssues=${count}`,
                message: 'Form switch height issues detected',
                explanation: 'Switch height is outside the component contract.',
                remediation: 'Update the control size to the approved height token.',
            }),
            countFindingRule({
                id: 'input-group-height',
                type: 'input-group-height',
                category: 'layout',
                severity: 'error',
                metricPath: 'metrics.inputGroupHeightIssues',
                legacyKey: (context, count) => `inputGroupHeightIssues=${count}`,
                message: 'Input group height issues detected',
                explanation: 'Input groups do not align to the expected component height.',
                remediation: 'Normalize the component height across all input group children.',
            }),
            countFindingRule({
                id: 'card-border-radius',
                type: 'card-border-radius',
                category: 'layout',
                severity: 'warning',
                metricPath: 'metrics.spacing.cardBorderRadiusIssues',
                legacyKey: (context, count) => `cardBorderRadiusMismatch=${count}`,
                message: 'Card border radius mismatch detected',
                explanation: 'Card corners do not match the contract or neighbor components.',
                remediation: 'Align the border radius with the card design token.',
            }),
        ],
    };
}
