services:
  wirebuddy:
    image: docker.cirrio.de/wirebuddy:latest
    container_name: wirebuddy
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      LOG_LEVEL: INFO # DEBUG
      WIREBUDDY_SECRET_KEY: "" # Generate with: head -c 32 /dev/urandom | base64
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./data:/app/data
