//
// tools/ui-lint/lib/device-runtime/devices/descriptors.mjs
// Copyright (C) 2026 Gill-Bates http://github.com/Gill-Bates
//

export const DEVICE_CATALOG = Object.freeze({
    'Desktop Chrome': Object.freeze({
        class: 'desktop',
        platform: 'desktop',
        viewport: { width: 1440, height: 1100 },
        deviceScaleFactor: 1,
        isMobile: false,
        hasTouch: false,
        touch: false,
        hover: true,
        pointer: 'fine',
        performanceTier: 'desktop',
        rendering: Object.freeze({
            fontSmoothing: 'subpixel-antialiased',
            overlayScrollbars: false,
            compositing: 'gpu',
            colorProfile: 'srgb',
        }),
        browserChromeInsets: Object.freeze({ top: 0, right: 0, bottom: 0, left: 0 }),
        networkProfile: 'online',
        supports: Object.freeze({ inert: true, backdropFilter: true, dynamicViewportUnits: true, scrollTimeline: true }),
        capabilities: Object.freeze({ touch: false, hover: true, pointer: 'fine', viewportSegments: 1, safeAreaInsets: false, dynamicViewport: false, virtualKeyboard: false }),
    }),
    'Desktop Firefox': Object.freeze({
        class: 'desktop',
        platform: 'desktop',
        viewport: { width: 1440, height: 1100 },
        deviceScaleFactor: 1,
        isMobile: false,
        hasTouch: false,
        touch: false,
        hover: true,
        pointer: 'fine',
        performanceTier: 'desktop',
        rendering: Object.freeze({
            fontSmoothing: 'grayscale',
            overlayScrollbars: false,
            compositing: 'gpu',
            colorProfile: 'srgb',
        }),
        browserChromeInsets: Object.freeze({ top: 0, right: 0, bottom: 0, left: 0 }),
        networkProfile: 'online',
        supports: Object.freeze({ inert: true, backdropFilter: true, dynamicViewportUnits: true, scrollTimeline: false }),
        capabilities: Object.freeze({ touch: false, hover: true, pointer: 'fine', viewportSegments: 1, safeAreaInsets: false, dynamicViewport: false, virtualKeyboard: false }),
    }),
    'Desktop Safari': Object.freeze({
        class: 'desktop',
        platform: 'desktop',
        viewport: { width: 1440, height: 1100 },
        deviceScaleFactor: 1,
        isMobile: false,
        hasTouch: false,
        touch: false,
        hover: true,
        pointer: 'fine',
        performanceTier: 'desktop',
        rendering: Object.freeze({
            fontSmoothing: 'subpixel-antialiased',
            overlayScrollbars: true,
            compositing: 'gpu',
            colorProfile: 'display-p3',
        }),
        browserChromeInsets: Object.freeze({ top: 0, right: 0, bottom: 0, left: 0 }),
        networkProfile: 'online',
        supports: Object.freeze({ inert: true, backdropFilter: true, dynamicViewportUnits: true, scrollTimeline: false }),
        capabilities: Object.freeze({ touch: false, hover: true, pointer: 'fine', viewportSegments: 1, safeAreaInsets: false, dynamicViewport: false, virtualKeyboard: false }),
    }),
    'iPhone 15': Object.freeze({
        class: 'mobile',
        platform: 'ios',
        viewport: { width: 393, height: 852 },
        deviceScaleFactor: 3,
        isMobile: true,
        hasTouch: true,
        touch: true,
        hover: false,
        pointer: 'coarse',
        performanceTier: 'mid-mobile',
        rendering: Object.freeze({
            fontSmoothing: 'subpixel-antialiased',
            overlayScrollbars: false,
            compositing: 'gpu',
            colorProfile: 'display-p3',
        }),
        browserChromeInsets: Object.freeze({ top: 44, right: 0, bottom: 34, left: 0 }),
        networkProfile: 'slow-4g',
        supports: Object.freeze({ inert: true, backdropFilter: true, dynamicViewportUnits: true, scrollTimeline: false }),
        capabilities: Object.freeze({ touch: true, hover: false, pointer: 'coarse', viewportSegments: 1, safeAreaInsets: true, dynamicViewport: true, virtualKeyboard: true }),
    }),
    'iPhone SE': Object.freeze({
        class: 'mobile',
        platform: 'ios',
        viewport: { width: 375, height: 667 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        touch: true,
        hover: false,
        pointer: 'coarse',
        performanceTier: 'low-end',
        rendering: Object.freeze({
            fontSmoothing: 'grayscale',
            overlayScrollbars: false,
            compositing: 'cpu',
            colorProfile: 'srgb',
        }),
        browserChromeInsets: Object.freeze({ top: 44, right: 0, bottom: 34, left: 0 }),
        networkProfile: 'slow-4g',
        supports: Object.freeze({ inert: true, backdropFilter: false, dynamicViewportUnits: true, scrollTimeline: false }),
        capabilities: Object.freeze({ touch: true, hover: false, pointer: 'coarse', viewportSegments: 1, safeAreaInsets: true, dynamicViewport: true, virtualKeyboard: true }),
    }),
    'Pixel 7': Object.freeze({
        class: 'mobile',
        platform: 'android',
        viewport: { width: 412, height: 915 },
        deviceScaleFactor: 2.625,
        isMobile: true,
        hasTouch: true,
        touch: true,
        hover: false,
        pointer: 'coarse',
        performanceTier: 'mid-mobile',
        rendering: Object.freeze({
            fontSmoothing: 'grayscale',
            overlayScrollbars: false,
            compositing: 'gpu',
            colorProfile: 'srgb',
        }),
        browserChromeInsets: Object.freeze({ top: 56, right: 0, bottom: 0, left: 0 }),
        networkProfile: 'slow-4g',
        supports: Object.freeze({ inert: true, backdropFilter: true, dynamicViewportUnits: true, scrollTimeline: false }),
        capabilities: Object.freeze({ touch: true, hover: false, pointer: 'coarse', viewportSegments: 1, safeAreaInsets: false, dynamicViewport: true, virtualKeyboard: true }),
    }),
    'iPad Pro 11': Object.freeze({
        class: 'tablet',
        platform: 'ios',
        viewport: { width: 834, height: 1194 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        touch: true,
        hover: false,
        pointer: 'coarse',
        performanceTier: 'tablet',
        rendering: Object.freeze({
            fontSmoothing: 'subpixel-antialiased',
            overlayScrollbars: false,
            compositing: 'gpu',
            colorProfile: 'display-p3',
        }),
        browserChromeInsets: Object.freeze({ top: 24, right: 0, bottom: 20, left: 0 }),
        networkProfile: 'online',
        supports: Object.freeze({ inert: true, backdropFilter: true, dynamicViewportUnits: true, scrollTimeline: false }),
        capabilities: Object.freeze({ touch: true, hover: false, pointer: 'coarse', viewportSegments: 1, safeAreaInsets: true, dynamicViewport: true, virtualKeyboard: true }),
    }),
    'iPad Mini': Object.freeze({
        class: 'tablet',
        platform: 'ios',
        viewport: { width: 744, height: 1133 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        touch: true,
        hover: false,
        pointer: 'coarse',
        performanceTier: 'tablet',
        rendering: Object.freeze({
            fontSmoothing: 'subpixel-antialiased',
            overlayScrollbars: false,
            compositing: 'gpu',
            colorProfile: 'display-p3',
        }),
        browserChromeInsets: Object.freeze({ top: 24, right: 0, bottom: 20, left: 0 }),
        networkProfile: 'online',
        supports: Object.freeze({ inert: true, backdropFilter: true, dynamicViewportUnits: true, scrollTimeline: false }),
        capabilities: Object.freeze({ touch: true, hover: false, pointer: 'coarse', viewportSegments: 1, safeAreaInsets: true, dynamicViewport: true, virtualKeyboard: true }),
    }),
    'Galaxy Z Fold 5': Object.freeze({
        class: 'foldable',
        platform: 'android',
        viewport: { width: 344, height: 882 },
        deviceScaleFactor: 2.625,
        isMobile: true,
        hasTouch: true,
        touch: true,
        hover: false,
        pointer: 'coarse',
        performanceTier: 'foldable',
        rendering: Object.freeze({
            fontSmoothing: 'grayscale',
            overlayScrollbars: false,
            compositing: 'gpu',
            colorProfile: 'srgb',
        }),
        browserChromeInsets: Object.freeze({ top: 56, right: 0, bottom: 0, left: 0 }),
        networkProfile: 'slow-4g',
        supports: Object.freeze({ inert: true, backdropFilter: true, dynamicViewportUnits: true, scrollTimeline: false }),
        capabilities: Object.freeze({ touch: true, hover: false, pointer: 'coarse', viewportSegments: 2, safeAreaInsets: true, dynamicViewport: true, virtualKeyboard: true }),
        foldable: Object.freeze({
            foldState: 'open',
            viewportSegments: [
                { index: 0, bounds: { x: 0, y: 0, width: 168, height: 882 } },
                { index: 1, bounds: { x: 176, y: 0, width: 168, height: 882 } },
            ],
            hingeBounds: { x: 168, y: 0, width: 8, height: 882 },
        }),
    }),
});

export const DEVICE_CATEGORIES = Object.freeze({
    desktop: ['Desktop Chrome', 'Desktop Firefox', 'Desktop Safari'],
    mobile: ['iPhone 15', 'iPhone SE', 'Pixel 7'],
    tablet: ['iPad Pro 11', 'iPad Mini'],
    foldable: ['Galaxy Z Fold 5'],
});

export const DEFAULT_MATRIX = Object.freeze([
    { browser: 'chromium', device: 'Desktop Chrome', scenario: 'desktop-default' },
    { browser: 'webkit', device: 'iPhone 15', scenario: 'one-handed-mobile' },
    { browser: 'webkit', device: 'iPad Pro 11', scenario: 'landscape-tablet' },
]);

export const EXTENDED_MATRIX = Object.freeze([
    { browser: 'chromium', device: 'Desktop Chrome', scenario: 'desktop-default' },
    { browser: 'firefox', device: 'Desktop Firefox', scenario: 'desktop-default' },
    { browser: 'webkit', device: 'Desktop Safari', scenario: 'desktop-default' },
    { browser: 'webkit', device: 'iPhone 15', scenario: 'one-handed-mobile' },
    { browser: 'chromium', device: 'iPhone 15', scenario: 'responsive-drift' },
    { browser: 'webkit', device: 'iPhone SE', scenario: 'low-end-mobile' },
    { browser: 'firefox', device: 'Pixel 7', scenario: 'low-end-android' },
    { browser: 'webkit', device: 'iPad Pro 11', scenario: 'landscape-tablet' },
    { browser: 'webkit', device: 'iPad Mini', scenario: 'portrait-tablet' },
    { browser: 'chromium', device: 'Galaxy Z Fold 5', scenario: 'foldable-open' },
]);

export const CUSTOM_VIEWPORTS = Object.freeze({
    'Desktop 1080p': Object.freeze({
        viewport: { width: 1920, height: 1080 },
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        deviceScaleFactor: 1,
        isMobile: false,
        hasTouch: false,
        browser: 'chromium',
        platform: 'desktop',
        capabilities: { touch: false, hover: true, pointer: 'fine', viewportSegments: 1, safeAreaInsets: false, dynamicViewport: false, virtualKeyboard: false },
    }),
    'Desktop 768': Object.freeze({
        viewport: { width: 768, height: 1024 },
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        deviceScaleFactor: 1,
        isMobile: false,
        hasTouch: false,
        browser: 'chromium',
        platform: 'desktop',
        capabilities: { touch: false, hover: true, pointer: 'fine', viewportSegments: 1, safeAreaInsets: false, dynamicViewport: false, virtualKeyboard: false },
    }),
    'Desktop 576': Object.freeze({
        viewport: { width: 576, height: 900 },
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        deviceScaleFactor: 1,
        isMobile: false,
        hasTouch: false,
        browser: 'chromium',
        platform: 'desktop',
        capabilities: { touch: false, hover: true, pointer: 'fine', viewportSegments: 1, safeAreaInsets: false, dynamicViewport: false, virtualKeyboard: false },
    }),
});