//
// tools/ui-lint/lib/config/index.mjs
// Copyright (C) 2026 Gill-Bates http://github.com/Gill-Bates
//

export {
    TOKEN_CATEGORIES,
    TOKEN_CATEGORY_LOOKUP,
    TOKEN_CATEGORY_REGISTRY,
    TOKEN_SCHEMA,
    TOKEN_SCHEMA_VERSION,
    isValidTokenCategory,
} from './tokens/schema.mjs';
export {
    createTokenDiagnostics,
} from './tokens/diagnostics.mjs';
export {
    hasToken,
    resolveOptionalToken,
    resolveRequiredToken,
    resolveToken,
} from './tokens/resolver.mjs';
export {
    validateAuditConfig,
    validateTokenPath,
    validateTokenResolution,
} from './tokens/validation.mjs';

export {
    FOCUS_POLICY,
} from './accessibility/focus.mjs';
export {
    CLICK_TARGET_MIN_SIZE_PX,
    INPUT_GROUP_HEIGHT_EXPECTED_PX,
    INPUT_GROUP_HEIGHT_TOLERANCE_PX,
    STANDARD_BUTTON_HEIGHT_EXPECTED_PX,
    STANDARD_BUTTON_HEIGHT_TOLERANCE_PX,
    TOUCH_TARGET_POLICY,
} from './accessibility/touch-targets.mjs';
export {
    evaluateContrast,
    isLargeText,
    WCAG_CONTRAST,
    WCAG_CONTRAST_POLICY,
} from './accessibility/wcag.mjs';

export {
    FOOTER_POLICY,
    LAYOUT_POLICY,
    VERTICAL_GAP_MIN,
    VERTICAL_GAP_MAX,
    STACK_GAP_VARIANCE_TOLERANCE_PX,
    SCROLL_EDGE_CLEARANCE_MIN,
    GHOST_SCROLL_DELTA_MAX_PX,
    GHOST_SCROLL_MIN_HEIGHT_PX,
    OVERFLOW_POLICY,
    OVERFLOW_TOLERANCE_PX,
    FOOTER_OVERLAP_TOLERANCE_PX,
    FOOTER_Z_INDEX,
    VISUAL_DRIFT_THRESHOLD,
    LAYOUT_SHIFT_THRESHOLD,
    COMPONENT_LAYOUT_SHIFT_THRESHOLD_PX,
    FLEX_MIN_HEIGHT_ZERO_TOLERANCE_PX,
    LAYOUT_SPACING_POLICY,
    LAYOUT_STABILITY_POLICY,
} from './layout/policies.mjs';

export {
    APP_MOTION_RULES,
    MOTION_POLICY,
    MOTION_RESET_CSS,
    MOTION_SCOPE_SELECTOR,
    APP_SPECIFIC_MOTION_RESET_CSS,
    FULL_MOTION_RESET_CSS,
    TRANSITION_POLICY,
    buildMotionResetCSS,
} from './motion/policies.mjs';

export {
    BROWSER_SETTLE_MODIFIERS_MS,
    CPU_SETTLE_MODIFIERS_MS,
    DEVICE_SETTLE_MODIFIERS_MS,
    SCREENSHOT_BROWSERS,
    SCREENSHOT_CPU_PROFILES,
    SCREENSHOT_DEVICE_CLASSES,
    SCREENSHOT_TIMING_POLICY,
    SCREENSHOT_SETTLE_MS,
    TAB_SWITCH_SETTLE_MS,
    DETAILS_EXPAND_SETTLE_MS,
    COMPONENT_LAYOUT_SHIFT_SETTLE_MS,
    LOGIN_ERROR_SETTLE_MS,
    LOGIN_LOCKOUT_RESET_MS,
    LOGIN_TEST_STAGGER_MS,
    DIFF_THRESHOLD_POLICY,
    SETTLE_TIME_POLICY,
    calculateScreenshotSettleTime,
    getScreenshotSettleTime,
} from './screenshots/policies.mjs';

export {
    ABOUT_APPLICATION_DETAILS_FORBIDDEN_ROWS,
    ABOUT_APPLICATION_DETAILS_REQUIRED_ROWS,
    ABOUT_MOBILE_STACK_GAP_VARIANCE_TOLERANCE_PX,
    ABOUT_TOP_ROW_HEIGHT_TOLERANCE_PX,
    ABOUT_UPDATE_TABLE_LABELS,
    BADGE_CONTRACT,
    BADGE_FONT_SIZE_TOLERANCE_PX,
    BADGE_FONT_WEIGHT_TOLERANCE,
    BADGE_PADDING_TOLERANCE_PX,
    BADGE_RADIUS_EXPECTED_PX,
    BADGE_RADIUS_TOLERANCE_PX,
    CARD_BORDER_RADIUS_EXPECTED_PX,
    CARD_BORDER_RADIUS_TOLERANCE_PX,
    CARD_CONTRACT,
    COMPACT_CARD_ACTION_BORDER_TOP_MAX_PX,
    COMPACT_CARD_ACTION_MARGIN_TOP_MAX_PX,
    COMPACT_CARD_ACTION_PADDING_TOP_MAX_PX,
    DASHBOARD_COMPACT_KPI_CARD_PADDING_EXPECTED,
    DASHBOARD_COMPACT_KPI_CARD_PADDING_TOLERANCE,
    DASHBOARD_COMPACT_KPI_ICON_MAX,
    DASHBOARD_COMPACT_KPI_ICON_MIN,
    DASHBOARD_TRANSFER_COLOR_DISTANCE_MIN,
    FORM_CONTRACT,
    FORM_SWITCH_HEIGHT_TOLERANCE_PX,
    FORM_SWITCH_MAX_HEIGHT_PX,
    KPI_CARD_CONTRACT,
    KPI_CARD_PADDING_EXPECTED,
    KPI_CARD_PADDING_TOLERANCE,
    KPI_CARD_REQUIRED_SCOPES,
    KPI_CONTEXTUAL_ICON_CLASSES,
    KPI_HEIGHT_TOLERANCE_PX,
    KPI_ICON_CENTER_TOLERANCE_PX,
    KPI_ICON_MAX,
    KPI_ICON_MIN,
    KPI_ICON_NEUTRAL_COLOR_DISTANCE_MAX,
    KPI_ROW_VARIANCE_MAX,
    KPI_VISUAL_DRIFT_THRESHOLD,
    LOGS_DELETE_HAIRLINE_TOLERANCE_PX,
    MODAL_CONTRACT,
    MODAL_BACKDROP_ALPHA_EXPECTED,
    MODAL_BACKDROP_ALPHA_TOLERANCE,
    MODAL_BACKDROP_BLUR_EXPECTED_PX,
    MODAL_BACKDROP_BLUR_TOLERANCE_PX,
    MODAL_BACKDROP_SATURATE_EXPECTED,
    MODAL_BACKDROP_SATURATE_TOLERANCE,
    MONOSPACE_PADDING_TOLERANCE_PX,
    MONOSPACE_RADIUS_TOLERANCE_PX,
    MONOSPACE_VERTICAL_INSET_TOLERANCE_PX,
    SETTINGS_TAB_COLOR_DISTANCE_MAX,
    SLIDER_CONTRACT,
    SLIDER_LABEL_HIDDEN_OPACITY_MAX,
    SLIDER_TICK_ALIGNMENT_TOLERANCE_PX,
    SLIDER_VISIBLE_LABEL_GAP_MIN_PX,
    STATUS_CONTRACT,
    STATUS_DETAIL_CARD_TITLES,
    STATUS_FLOW_CONNECTOR_EXPECTATIONS,
    STATUS_FLOW_NODE_EXPECTATIONS,
    getComponentContract,
    getComponentContracts,
    registerComponentContract,
} from './components/contracts.mjs';

export {
    BROWSER_CAPABILITIES,
    DEFAULT_EVALUATION_CATEGORIES,
    DEVICE_PROFILE_REGISTRY,
    MOTION_MODES,
    PAYLOAD_MODES,
    UI_LINT_PROFILES,
    buildEvaluationPayload,
    buildSerializableConstants,
} from './runtime/policies.mjs';
export {
    UI_EVAL_CONSTANTS,
} from './runtime/evaluate-payloads.mjs';

export {
    CONTRAST_MODES,
    THEME_REGISTRY,
    THEMES,
    getThemeRegistry,
    registerTheme,
} from './themes/themes.mjs';